# Install script for directory: C:/Users/spiecs/Documents/NVIDIA Nsight Graphics/CppCaptures/SpicesGame__2024_07_21__11_34_38

# Set the install prefix
if(NOT DEFINED CMAKE_INSTALL_PREFIX)
  set(CMAKE_INSTALL_PREFIX "C:/Program Files/SpicesGame__2024_07_21__11_34_38")
endif()
string(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
if(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)
  if(BUILD_TYPE)
    string(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  else()
    set(CMAKE_INSTALL_CONFIG_NAME "Release")
  endif()
  message(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
endif()

# Set the component getting installed.
if(NOT CMAKE_INSTALL_COMPONENT)
  if(COMPONENT)
    message(STATUS "Install component: \"${COMPONENT}\"")
    set(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  else()
    set(CMAKE_INSTALL_COMPONENT)
  endif()
endif()

# Is this installation the result of a crosscompile?
if(NOT DEFINED CMAKE_CROSSCOMPILING)
  set(CMAKE_CROSSCOMPILING "FALSE")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  if(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
     "C:/Users/spiecs/Documents/NVIDIA Nsight Graphics/CppCaptures/SpicesGame__2024_07_21__11_34_38/bin/SpicesGame.exe")
    if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    file(INSTALL DESTINATION "C:/Users/spiecs/Documents/NVIDIA Nsight Graphics/CppCaptures/SpicesGame__2024_07_21__11_34_38/bin" TYPE EXECUTABLE FILES "C:/Users/spiecs/Documents/NVIDIA Nsight Graphics/CppCaptures/SpicesGame__2024_07_21__11_34_38/int/Debug/SpicesGame.exe")
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
     "C:/Users/spiecs/Documents/NVIDIA Nsight Graphics/CppCaptures/SpicesGame__2024_07_21__11_34_38/bin/SpicesGame.exe")
    if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    file(INSTALL DESTINATION "C:/Users/spiecs/Documents/NVIDIA Nsight Graphics/CppCaptures/SpicesGame__2024_07_21__11_34_38/bin" TYPE EXECUTABLE FILES "C:/Users/spiecs/Documents/NVIDIA Nsight Graphics/CppCaptures/SpicesGame__2024_07_21__11_34_38/int/Release/SpicesGame.exe")
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
     "C:/Users/spiecs/Documents/NVIDIA Nsight Graphics/CppCaptures/SpicesGame__2024_07_21__11_34_38/bin/SpicesGame.exe")
    if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    file(INSTALL DESTINATION "C:/Users/spiecs/Documents/NVIDIA Nsight Graphics/CppCaptures/SpicesGame__2024_07_21__11_34_38/bin" TYPE EXECUTABLE FILES "C:/Users/spiecs/Documents/NVIDIA Nsight Graphics/CppCaptures/SpicesGame__2024_07_21__11_34_38/int/MinSizeRel/SpicesGame.exe")
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
     "C:/Users/spiecs/Documents/NVIDIA Nsight Graphics/CppCaptures/SpicesGame__2024_07_21__11_34_38/bin/SpicesGame.exe")
    if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    file(INSTALL DESTINATION "C:/Users/spiecs/Documents/NVIDIA Nsight Graphics/CppCaptures/SpicesGame__2024_07_21__11_34_38/bin" TYPE EXECUTABLE FILES "C:/Users/spiecs/Documents/NVIDIA Nsight Graphics/CppCaptures/SpicesGame__2024_07_21__11_34_38/int/RelWithDebInfo/SpicesGame.exe")
  endif()
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  if(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
     "C:/Users/spiecs/Documents/NVIDIA Nsight Graphics/CppCaptures/SpicesGame__2024_07_21__11_34_38/bin/GeneratedReplay.dll")
    if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    file(INSTALL DESTINATION "C:/Users/spiecs/Documents/NVIDIA Nsight Graphics/CppCaptures/SpicesGame__2024_07_21__11_34_38/bin" TYPE SHARED_LIBRARY FILES "C:/Users/spiecs/Documents/NVIDIA Nsight Graphics/CppCaptures/SpicesGame__2024_07_21__11_34_38/int/Debug/GeneratedReplay.dll")
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
     "C:/Users/spiecs/Documents/NVIDIA Nsight Graphics/CppCaptures/SpicesGame__2024_07_21__11_34_38/bin/GeneratedReplay.dll")
    if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    file(INSTALL DESTINATION "C:/Users/spiecs/Documents/NVIDIA Nsight Graphics/CppCaptures/SpicesGame__2024_07_21__11_34_38/bin" TYPE SHARED_LIBRARY FILES "C:/Users/spiecs/Documents/NVIDIA Nsight Graphics/CppCaptures/SpicesGame__2024_07_21__11_34_38/int/Release/GeneratedReplay.dll")
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
     "C:/Users/spiecs/Documents/NVIDIA Nsight Graphics/CppCaptures/SpicesGame__2024_07_21__11_34_38/bin/GeneratedReplay.dll")
    if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    file(INSTALL DESTINATION "C:/Users/spiecs/Documents/NVIDIA Nsight Graphics/CppCaptures/SpicesGame__2024_07_21__11_34_38/bin" TYPE SHARED_LIBRARY FILES "C:/Users/spiecs/Documents/NVIDIA Nsight Graphics/CppCaptures/SpicesGame__2024_07_21__11_34_38/int/MinSizeRel/GeneratedReplay.dll")
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
     "C:/Users/spiecs/Documents/NVIDIA Nsight Graphics/CppCaptures/SpicesGame__2024_07_21__11_34_38/bin/GeneratedReplay.dll")
    if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    file(INSTALL DESTINATION "C:/Users/spiecs/Documents/NVIDIA Nsight Graphics/CppCaptures/SpicesGame__2024_07_21__11_34_38/bin" TYPE SHARED_LIBRARY FILES "C:/Users/spiecs/Documents/NVIDIA Nsight Graphics/CppCaptures/SpicesGame__2024_07_21__11_34_38/int/RelWithDebInfo/GeneratedReplay.dll")
  endif()
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  if(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
     "C:/Users/spiecs/Documents/NVIDIA Nsight Graphics/CppCaptures/SpicesGame__2024_07_21__11_34_38/bin/ReplayExecutor.dll")
    if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    file(INSTALL DESTINATION "C:/Users/spiecs/Documents/NVIDIA Nsight Graphics/CppCaptures/SpicesGame__2024_07_21__11_34_38/bin" TYPE SHARED_LIBRARY FILES "C:/Users/spiecs/Documents/NVIDIA Nsight Graphics/CppCaptures/SpicesGame__2024_07_21__11_34_38/int/Debug/ReplayExecutor.dll")
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
     "C:/Users/spiecs/Documents/NVIDIA Nsight Graphics/CppCaptures/SpicesGame__2024_07_21__11_34_38/bin/ReplayExecutor.dll")
    if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    file(INSTALL DESTINATION "C:/Users/spiecs/Documents/NVIDIA Nsight Graphics/CppCaptures/SpicesGame__2024_07_21__11_34_38/bin" TYPE SHARED_LIBRARY FILES "C:/Users/spiecs/Documents/NVIDIA Nsight Graphics/CppCaptures/SpicesGame__2024_07_21__11_34_38/int/Release/ReplayExecutor.dll")
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
     "C:/Users/spiecs/Documents/NVIDIA Nsight Graphics/CppCaptures/SpicesGame__2024_07_21__11_34_38/bin/ReplayExecutor.dll")
    if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    file(INSTALL DESTINATION "C:/Users/spiecs/Documents/NVIDIA Nsight Graphics/CppCaptures/SpicesGame__2024_07_21__11_34_38/bin" TYPE SHARED_LIBRARY FILES "C:/Users/spiecs/Documents/NVIDIA Nsight Graphics/CppCaptures/SpicesGame__2024_07_21__11_34_38/int/MinSizeRel/ReplayExecutor.dll")
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
     "C:/Users/spiecs/Documents/NVIDIA Nsight Graphics/CppCaptures/SpicesGame__2024_07_21__11_34_38/bin/ReplayExecutor.dll")
    if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    file(INSTALL DESTINATION "C:/Users/spiecs/Documents/NVIDIA Nsight Graphics/CppCaptures/SpicesGame__2024_07_21__11_34_38/bin" TYPE SHARED_LIBRARY FILES "C:/Users/spiecs/Documents/NVIDIA Nsight Graphics/CppCaptures/SpicesGame__2024_07_21__11_34_38/int/RelWithDebInfo/ReplayExecutor.dll")
  endif()
endif()

if(CMAKE_INSTALL_COMPONENT)
  set(CMAKE_INSTALL_MANIFEST "install_manifest_${CMAKE_INSTALL_COMPONENT}.txt")
else()
  set(CMAKE_INSTALL_MANIFEST "install_manifest.txt")
endif()

string(REPLACE ";" "\n" CMAKE_INSTALL_MANIFEST_CONTENT
       "${CMAKE_INSTALL_MANIFEST_FILES}")
file(WRITE "C:/Users/spiecs/Documents/NVIDIA Nsight Graphics/CppCaptures/SpicesGame__2024_07_21__11_34_38/int/${CMAKE_INSTALL_MANIFEST}"
     "${CMAKE_INSTALL_MANIFEST_CONTENT}")
